package myprototype.jparse;

import myprototype.jparse.symbol.Production;
import myprototype.jparse.symbol.terminal.BooleanLiteralToken;
import myprototype.jparse.symbol.terminal.CharacterLiteralToken;
import myprototype.jparse.symbol.terminal.FloatingPointLiteralToken;
import myprototype.jparse.symbol.terminal.IdentifierToken;
import myprototype.jparse.symbol.terminal.IntegerLiteralToken;
import myprototype.jparse.symbol.terminal.NullLiteralToken;
import myprototype.jparse.symbol.terminal.StringLiteralToken;
import myprototype.jparse.symbol.terminal.keyword.AbstractKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.AssertKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.BooleanKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.BreakKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.ByteKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.CaseKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.CatchKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.CharKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.ClassKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.ConstKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.ContinueKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.DefaultKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.DoKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.DoubleKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.ElseKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.EnumKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.ExtendsKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.FinalKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.FinallyKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.FloatKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.ForKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.GotoKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.IfKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.ImplementsKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.ImportKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.InstanceofKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.IntKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.InterfaceKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.LongKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.NativeKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.NewKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.PackageKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.PrivateKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.ProtectedKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.PublicKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.ReturnKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.ShortKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.StaticKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.StrictfpKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.SuperKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.SwitchKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.SynchronizedKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.ThisKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.ThrowKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.ThrowsKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.TransientKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.TryKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.VoidKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.VolatileKeywordToken;
import myprototype.jparse.symbol.terminal.keyword.WhileKeywordToken;

public class LRTable {
	public static void main(String[] args) {
		Production<BooleanLiteralToken> booleanLiteralTokenProduction = new Production<>(BooleanLiteralToken.class);
		Production<CharacterLiteralToken> characterLiteralTokenProduction = new Production<>(CharacterLiteralToken.class);
		Production<FloatingPointLiteralToken> floatingPointLiteralTokenProduction = new Production<>(FloatingPointLiteralToken.class);
		Production<IdentifierToken> identifierTokenProduction = new Production<>(IdentifierToken.class);
		Production<IntegerLiteralToken> integerLiteralTokenProduction = new Production<>(IntegerLiteralToken.class);
		Production<NullLiteralToken> nullLiteralTokenProduction = new Production<>(NullLiteralToken.class);
		Production<StringLiteralToken> stringLiteralTokenProduction = new Production<>(StringLiteralToken.class);
		
		Production<AbstractKeywordToken> abstractKeywordTokenProduction = new Production<>(AbstractKeywordToken.class);
		Production<ContinueKeywordToken> continueKeywordTokenProduction = new Production<>(ContinueKeywordToken.class);
		Production<ForKeywordToken> forKeywordTokenProduction = new Production<>(ForKeywordToken.class);
		Production<NewKeywordToken> newKeywordTokenProduction = new Production<>(NewKeywordToken.class);
		Production<SwitchKeywordToken> switchKeywordTokenProduction = new Production<>(SwitchKeywordToken.class);
		Production<AssertKeywordToken> assertKeywordTokenProduction = new Production<>(AssertKeywordToken.class);
		Production<DefaultKeywordToken> defaultKeywordTokenProduction = new Production<>(DefaultKeywordToken.class);
		Production<IfKeywordToken> ifKeywordTokenProduction = new Production<>(IfKeywordToken.class);
		Production<PackageKeywordToken> packageKeywordTokenProduction = new Production<>(PackageKeywordToken.class);
		Production<SynchronizedKeywordToken> synchronizedKeywordTokenProduction = new Production<>(SynchronizedKeywordToken.class);
		Production<BooleanKeywordToken> booleanKeywordTokenProduction = new Production<>(BooleanKeywordToken.class);
		Production<DoKeywordToken> doKeywordTokenProduction = new Production<>(DoKeywordToken.class);
		Production<GotoKeywordToken> gotoKeywordTokenProduction = new Production<>(GotoKeywordToken.class);
		Production<PrivateKeywordToken> privateKeywordTokenProduction = new Production<>(PrivateKeywordToken.class);
		Production<ThisKeywordToken> thisKeywordTokenProduction = new Production<>(ThisKeywordToken.class);
		Production<BreakKeywordToken> breakKeywordTokenProduction = new Production<>(BreakKeywordToken.class);
		Production<DoubleKeywordToken> doubleKeywordTokenProduction = new Production<>(DoubleKeywordToken.class);
		Production<ImplementsKeywordToken> implementsKeywordTokenProduction = new Production<>(ImplementsKeywordToken.class);
		Production<ProtectedKeywordToken> protectedKeywordTokenProduction = new Production<>(ProtectedKeywordToken.class);
		Production<ThrowKeywordToken> throwKeywordTokenProduction = new Production<>(ThrowKeywordToken.class);
		Production<ByteKeywordToken> byteKeywordTokenProduction = new Production<>(ByteKeywordToken.class);
		Production<ElseKeywordToken> elseKeywordTokenProduction = new Production<>(ElseKeywordToken.class);
		Production<ImportKeywordToken> importKeywordTokenProduction = new Production<>(ImportKeywordToken.class);
		Production<PublicKeywordToken> publicKeywordTokenProduction = new Production<>(PublicKeywordToken.class);
		Production<ThrowsKeywordToken> throwsKeywordTokenProduction = new Production<>(ThrowsKeywordToken.class);
		Production<CaseKeywordToken> caseKeywordTokenProduction = new Production<>(CaseKeywordToken.class);
		Production<EnumKeywordToken> enumKeywordTokenProduction = new Production<>(EnumKeywordToken.class);
		Production<InstanceofKeywordToken> instanceofKeywordTokenProduction = new Production<>(InstanceofKeywordToken.class);
		Production<ReturnKeywordToken> returnKeywordTokenProduction = new Production<>(ReturnKeywordToken.class);
		Production<TransientKeywordToken> transientKeywordTokenProduction = new Production<>(TransientKeywordToken.class);
		Production<CatchKeywordToken> catchKeywordTokenProduction = new Production<>(CatchKeywordToken.class);
		Production<ExtendsKeywordToken> extendsKeywordTokenProduction = new Production<>(ExtendsKeywordToken.class);
		Production<IntKeywordToken> intKeywordTokenProduction = new Production<>(IntKeywordToken.class);
		Production<ShortKeywordToken> shortKeywordTokenProduction = new Production<>(ShortKeywordToken.class);
		Production<TryKeywordToken> tryKeywordTokenProduction = new Production<>(TryKeywordToken.class);
		Production<CharKeywordToken> charKeywordTokenProduction = new Production<>(CharKeywordToken.class);
		Production<FinalKeywordToken> finalKeywordTokenProduction = new Production<>(FinalKeywordToken.class);
		Production<InterfaceKeywordToken> interfaceKeywordTokenProduction = new Production<>(InterfaceKeywordToken.class);
		Production<StaticKeywordToken> staticKeywordTokenProduction = new Production<>(StaticKeywordToken.class);
		Production<VoidKeywordToken> voidKeywordTokenProduction = new Production<>(VoidKeywordToken.class);
		Production<ClassKeywordToken> classKeywordTokenProduction = new Production<>(ClassKeywordToken.class);
		Production<FinallyKeywordToken> finallyKeywordTokenProduction = new Production<>(FinallyKeywordToken.class);
		Production<LongKeywordToken> longKeywordTokenProduction = new Production<>(LongKeywordToken.class);
		Production<StrictfpKeywordToken> strictfpKeywordTokenProduction = new Production<>(StrictfpKeywordToken.class);
		Production<VolatileKeywordToken> volatileKeywordTokenProduction = new Production<>(VolatileKeywordToken.class);
		Production<ConstKeywordToken> constKeywordTokenProduction = new Production<>(ConstKeywordToken.class);
		Production<FloatKeywordToken> floatKeywordTokenProduction = new Production<>(FloatKeywordToken.class);
		Production<NativeKeywordToken> nativeKeywordTokenProduction = new Production<>(NativeKeywordToken.class);
		Production<SuperKeywordToken> superKeywordTokenProduction = new Production<>(SuperKeywordToken.class);
		Production<WhileKeywordToken> whileKeywordTokenProduction = new Production<>(WhileKeywordToken.class);
		
		
		
	}
}
