package myprototype.jparse.symbol;

public enum SymbolEnum implements SymbolEnumProtocol {
	// * My Test Nonterminal Symbols
	// S -> Exp
	// Exp -> + Exp Exp
	// Exp -> - Exp Exp
	// Exp -> * Exp Exp
	// Exp -> / Exp Exp
	// Exp -> ( Exp )
	// Exp -> DIGIT

	S(SymbolKindEnum.NONTERMINAL),
	EXP(SymbolKindEnum.NONTERMINAL),
	// DIGIT -> INTEGER_LITERAL_TOKEN
	
	
	
	
	// * Nonterminal Symbols
	EXPRESSION_NODE(SymbolKindEnum.NONTERMINAL),
	
	// * Terminal Symbols
	
	// ** Literal Tokens
	BOOLEAN_LITERAL_TOKEN(SymbolKindEnum.TERMINAL),
	CHARACTER_LITERAL_TOKEN(SymbolKindEnum.TERMINAL),
	FLOATING_POINT_LITERAL_TOKEN(SymbolKindEnum.TERMINAL),
	IDENTIFIER_TOKEN(SymbolKindEnum.TERMINAL),
	INTEGER_LITERAL_TOKEN(SymbolKindEnum.TERMINAL),
	NULL_LITERAL_TOKEN(SymbolKindEnum.TERMINAL),
	STRING_LITERAL_TOKEN(SymbolKindEnum.TERMINAL),
	
	// ** Separator Tokens
	ROUND_BRACKET_OPEN_SEPARATOR_TOKEN(SymbolKindEnum.TERMINAL),
	ROUND_BRACKET_CLOSE_SEPARATOR_TOKEN(SymbolKindEnum.TERMINAL),
	CURLY_BRACKET_OPEN_SEPARATOR_TOKEN(SymbolKindEnum.TERMINAL),
	CURLY_BRACKET_CLOSE_SEPARATOR_TOKEN(SymbolKindEnum.TERMINAL),
	SQUARE_BRACKET_OPEN_SEPARATOR_TOKEN(SymbolKindEnum.TERMINAL),
	SQUARE_BRACKET_CLOSE_SEPARATOR_TOKEN(SymbolKindEnum.TERMINAL),
	SEMICOLON_SEPARATOR_TOKEN(SymbolKindEnum.TERMINAL),
	COMMA_SEPARATOR_TOKEN(SymbolKindEnum.TERMINAL),
	PERIOD_SEPARATOR_TOKEN(SymbolKindEnum.TERMINAL),

	// ** Operator Tokens
	ASSIGNMENT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	EQUAL_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	GREATER_THAN_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	GREATER_THAN_EQUAL_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	RIGHT_SHIFT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	RIGHT_SHIFT_ASSIGNMENT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	UNSIGNED_RIGHT_SHIFT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	LESS_THAN_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	LESS_THAN_EQUAL_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	LEFT_SHIFT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	LEFT_SHIFT_ASSIGNMENT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	LOGICAL_NOT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	NOT_EQUAL_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	BITWISE_NOT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	CONDITIONAL_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	COLON_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	BITWISE_AND_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	BITWISE_AND_ASSIGNMENT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	LOGICAL_AND_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	BITWISE_OR_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	BITWISE_OR_ASSIGNMENT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	LOGICAL_OR_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	ADDITION_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	ADDITION_ASSIGNMENT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	INCREMENT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	SUBTRACTION_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	SUBTRACTION_ASSIGNMENT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	DECREMENT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	MULTIPLICATION_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	MULTIPLICATION_ASSIGNMENT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	DIVISION_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	DIVISION_ASSIGNMENT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	BITWISE_XOR_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	BITWISE_XOR_ASSIGNMENT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	MODULO_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),
	MODULO_ASSIGNMENT_OPERATOR_TOKEN(SymbolKindEnum.TERMINAL),

	// ** Keyword Tokens
	ABSTRACT_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	CONTINUE_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	FOR_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	NEW_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	SWITCH_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	ASSERT_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	DEFAULT_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	IF_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	PACKAGE_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	SYNCHRONIZED_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	BOOLEAN_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	DO_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	GOTO_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	PRIVATE_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	THIS_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	BREAK_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	DOUBLE_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	IMPLEMENTS_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	PROTECTED_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	THROW_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	BYTE_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	ELSE_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	IMPORT_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	PUBLIC_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	THROWS_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	CASE_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	ENUM_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	INSTANCEOF_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	RETURN_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	TRANSIENT_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	CATCH_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	EXTENDS_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	INT_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	SHORT_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	TRY_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	CHAR_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	FINAL_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	INTERFACE_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	STATIC_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	VOID_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	CLASS_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	FINALLY_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	LONG_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	STRICTFP_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	VOLATILE_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	CONST_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	FLOAT_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	NATIVE_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	SUPER_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	WHILE_KEYWORD_TOKEN(SymbolKindEnum.TERMINAL),
	
	;
	
	private SymbolKindEnum kind;

	@Override
	public SymbolKindEnum getKind() {
		return this.kind;
	}
	
	private SymbolEnum(SymbolKindEnum kind) {
		this.kind = kind;
	}
}
